#!/usr/bin/env bash
# Displays the time for 12 hour and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

hour=0
while (( hour <= 12 ))
do
	minute=1
	echo "Hour: $hour"
	while (( minute <= 59 ))
	do
		echo "$minute"
		(( minute++ ))
	done
   	(( hour++ ))
done
